version: '3.8'
services:
  php-apache-environment:
    container_name: php-apache
    build:
      context: ./php
      dockerfile: Dockerfile
    depends_on:
      - composer
    volumes:
      - ./php/src:/var/www/html/
      - ./php/src/.htaccess:/var/www/html/.htaccess
    ports:
      - 8000:80
    networks:
      - dmsh-network
  composer:
    image: composer:1.9
    command: [ "composer", "update" ]
    volumes:
      - ./php/src:/app
networks:
  dmsh-network:
    name: dmsh-network
    driver: bridge